package com.mauricio.adaptiveperformance;
import android.content.SharedPreferences;
import java.util.HashMap;
import java.util.Map;
/** App language choice, independent of the Android system language. */
final class UiLanguage {
    private static final Map<String,String> EN = new HashMap<>();
    private static void put(String pt,String en){ EN.put(pt,en); }
    static {
        put("Modo de uso","Operating mode");
        put("Automático para simplicidade ou Avançado para controle total","Automatic for simplicity or Advanced for full control");
        put("Automático","Automatic");
        put("Avançado","Advanced");
        put("Otimização automática","Automatic optimization");
        put("O aplicativo escolhe e testa as melhores configurações por você","The app evaluates settings and keeps only measurable improvements");
        put("Monitoramento inteligente do sistema","Intelligent system monitoring");
        put("Estado atual","Current status");
        put("Equilibrado","Balanced");
        put("Desempenho e temperatura sob controle","Performance and temperature under control");
        put("Proteção térmica","Thermal protection");
        put("Escolha um nível travado de 1 a 5 ou use o modo automático","Lock a level from 1 to 5 or use automatic mode");
        put("Ações inteligentes","Smart actions");
        put("Automatize estabilidade, temperatura e segundo plano","Automate stability, temperature and background activity");
        put("Sistema e serviço","System and service");
        put("Shizuku, monitor e controles do aplicativo","Shizuku, monitoring and app controls");
        put("Apps que mais gastam bateria","Apps using the most battery");
        put("Ranking atual","Current ranking");
        put("Atividade recente","Recent activity");
        put("Últimas mudanças","Latest changes");
        put("Apps restritos por inatividade","Apps restricted due to inactivity");
        put("Restrições automáticas reversíveis","Reversible automatic restrictions");
        put("Modo simples","Simple mode");
        put("Otimizações compatíveis com Android, sem ADB ou Shizuku","Android-compatible optimization without ADB or Shizuku");
        put("⌂\nInício","⌂\nHome");
        put("✦\nLimpeza","✦\nCleanup");
        put("⚙\nAjustes","⚙\nSettings");
        put("Meta de bateria","Battery target");
        put("Bateria mínima: ","Minimum battery: ");
        put("Horário alvo: ","Target time: ");
        put("Consumo e autonomia estimada","Estimated consumption and battery life");
        put("Aguardando dados…","Waiting for data…");
        put("Parar otimização","Stop optimization");
        put("Iniciar otimização","Start optimization");
        put("Autorizar Shizuku","Authorize Shizuku");
        put("Abrir Shizuku","Open Shizuku");
        put("Pré-carregar apps usados agora","Preload recently used apps now");
        put("Reiniciar aprendizado automático","Reset automatic learning");
        put("Abrir ações inteligentes","Open smart actions");
        put("Ver o que está limitando agora","View current restrictions");
        put("Histórico de incidentes e correções","Incident and repair history");
        put("Painel de economia e automação","Battery savings and automation dashboard");
        put("❄  Selecionar apps para congelar","❄  Select apps to freeze");
        put("Apps que nunca devem ser congelados automaticamente","Apps never automatically frozen");
        put("Histórico de saúde — 24 horas","Health history — 24 hours");
        put("Exportar diagnóstico para Downloads","Export diagnostics to Downloads");
        put("Auto-Reparo com medição antes/depois","Auto-repair with before/after measurements");
        put("Pontuação de eficácia e histórico","Effectiveness score and history");
        put("Perfis por aplicativo","Per-app profiles");
        put("Proteção contra otimização excessiva","Prevent excessive optimization");
        put("RAM emergencial: <8% livre ou <15% + PSI ≥25","Emergency RAM: <8% free or <15% + PSI ≥25");
        put("Diagnóstico na inicialização","Startup diagnostics");
        put("Aprender padrões por horário e uso","Learn usage patterns by time");
        put("Exigir confiança mínima antes de Auto-Reparo","Require minimum confidence before auto-repair");
        put("Detectar recidiva e variar estratégia","Detect recurrence and change strategy");
        put("Observar 60 s após correções antes de agir novamente","Wait 60 s after fixes before new actions");
        put("Detectar regressão de consumo após atualização de apps","Detect higher consumption after app updates");
        put("Modo somente diagnóstico: não alterar o sistema","Diagnostics only: do not change the system");
        put("Reduzir a tela para 60 Hz somente com aquecimento","Limit display to 60 Hz only when hot");
        put("Liberar processos em cache quando RAM livre < 7%","Release cached processes when free RAM < 7%");
        put("Compactação automática de RAM","Automatic RAM compaction");
        put("Modo automático geral: RAM + PSI + temperatura + bateria","General auto mode: RAM + PSI + temperature + battery");
        put("Limpeza automática com pouco armazenamento e tela apagada","Automatic cleanup for low storage when screen is off");
        put("Congelamento adaptativo de apps ociosos/restritos","Adaptive freezing of idle/restricted apps");
        put("Detectar processos que reiniciam repetidamente","Detect repeatedly restarting processes");
        put("Modo automático de bateria baixa (≤25%)","Automatic low-battery mode (≤25%)");
        put("Proteção contra thrashing da ZRAM/swap","Protect against ZRAM/swap thrashing");
        put("Usar PSI real de CPU, memória e I/O nas decisões","Use real CPU, memory and I/O pressure (PSI)");
        put("Perfis automáticos Econômico/Balanceado/Desempenho por app","Automatic Eco/Balanced/Performance profiles");
        put("Detector de vazamento de RAM por tendência","Detect RAM leak trends");
        put("Controle térmico adaptativo gradual","Gradual adaptive thermal control");
        put("Limitar apps em segundo plano com RAM excessiva (limite individual suportado)","Limit background apps using excessive RAM");
        put("Modo RAM agressivo: agir quando RAM livre < 20%","Aggressive RAM mode when free RAM < 20%");
        put("Finalizar apps anormais travados em segundo plano","Stop abnormal stuck background apps");
        put("Restringir apps sem uso há mais de 3 dias","Restrict apps unused for over 3 days");
        put("Reduzir segundo plano quando CPU/VM/energia indicarem pressão","Reduce background work under CPU/VM/power pressure");
        put("Motor preditivo: temperatura + PSI + energia + armazenamento","Predictive engine: temperature + PSI + power + storage");
        put("Economia profunda e segura quando a tela estiver desligada","Safe deep power savings with screen off");
        put("Detectar wakeups excessivos e loops de rede","Detect excessive wakeups and network loops");
        put("Saúde avançada: jank + LMKD + zRAM + Jobs","Advanced health: jank + LMKD + zRAM + Jobs");
        put("Autocalibrar limites conforme o comportamento do aparelho","Auto-calibrate limits to device behavior");
        put("Aprender temperatura, CPU, RAM e energia de cada app","Learn app temperature, CPU, RAM and power");
        put("Modo anti-travamento preventivo","Preventive anti-stall mode");
        put("Guardar histórico de saúde das últimas 24 horas","Keep 24-hour health history");
        put("Rollback automático de restrições se piorarem a fluidez","Automatically undo restrictions that reduce smoothness");
        put("Conter apps em loop de crash/reinício","Contain apps in crash/restart loops");
        put("Diagnóstico estendido: ANR + Binder + GPU + sensores","Extended diagnostics: ANR + Binder + GPU + sensors");
        put("Prever aquecimento com 1–3 minutos de antecedência","Predict heating 1–3 minutes ahead");
        put("Modo diagnóstico de 10 min ao detectar anomalia","10-minute diagnostics on anomaly");
        put("Ajustar agressividade conforme estabilidade e consumo","Tune aggressiveness to stability and power");
        put("Teste A/B interno após autocalibração","Internal A/B testing after auto-calibration");
        put("Monitorar sensores, GPS, câmera, microfone e modem","Monitor sensors, GPS, camera, microphone and modem");
        put("Monitorar saturação de armazenamento/I/O","Monitor storage/I/O saturation");
        put("Detectar serviços de automação duplicados","Detect duplicate automation services");
        put("Monitorar deep sleep e Doze com a tela apagada","Monitor deep sleep and Doze with screen off");
        put("Detectar crescimento anormal de memória por aplicativo","Detect abnormal per-app memory growth");
        put("Reduzir brilho temporariamente em aquecimento forte","Temporarily lower brightness when hot");
        put("Economia sistêmica adaptativa","Adaptive system-wide power savings");
        put("Deep idle: pausar monitoramento e liberar Doze","Deep idle: pause monitoring and allow Doze");
        put("Economizar scans Wi-Fi e dados paralelos em repouso","Reduce Wi-Fi scans and idle background data");
        put("Gerenciar exceções do Doze automaticamente","Automatically manage Doze exceptions");
        put("Timeout da tela adaptativo (até 3 min em uso comum)","Adaptive screen timeout (up to 3 min)");
        put("Máxima economia: desativar dois-toques no repouso","Maximum savings: disable double-tap while idle");
        put("Forçar modo seguro dos módulos avançados","Force safe mode for advanced modules");
        put("Ativar congelamento manual dos apps selecionados","Enable manual freezing of selected apps");
        put("Notificar somente problemas que não puderem ser resolvidos","Notify only issues that could not be resolved");
        put("Preparando primeiro ciclo de testes","Preparing first test cycle");
        put("Aprendizado inicial • priorizando economia de bateria","Initial learning • prioritizing battery savings");
        put("Medindo referência","Measuring baseline");
        put("Testando","Testing");
        put("Mantido","Kept");
        put("Revertido","Reverted");
        put("teste revertido","trial reverted");
        put("Ciclo conservador concluído","Conservative cycle completed");
        put("CPU indisponível","CPU unavailable");
        put("medição indisponível","measurement unavailable");
        put("temperatura subiu","temperature increased");
        put("consumo disparou","power draw spiked");
        put("a temperatura aumentou","temperature increased");
        put("o uso de CPU aumentou","CPU usage increased");
        put("a RAM livre caiu","available RAM decreased");
        put("o consumo de energia aumentou","power consumption increased");
        put("não comprovou economia mensurável","no measurable saving proven");
        put("Pré-carregamento automático aguardando o próximo ciclo","Automatic preloading waiting for the next cycle");
        put("Apps mantidos neste ciclo: nenhum","No apps kept this cycle");
        put("Nenhum APK foi aquecido neste ciclo","No apps warmed up this cycle");
        put("Aguardando primeira leitura","Waiting for first reading");
        put("Monitor parado","Monitoring stopped");
        put("Sem testes concluídos","No completed tests");
        put("Proteção máxima ativa para reduzir o aquecimento","Maximum thermal protection enabled");
        put("Proteção térmica automática em ação","Automatic thermal protection active");
        put("Modo anti-travamento forte em ação","Strong anti-stall mode active");
        put("Prevenção de travamentos ativa","Anti-stall protection active");
        put("Apps em segundo plano temporariamente limitados","Background apps temporarily limited");
        put("Nenhuma limitação ativa","No restrictions active");
        put("Coletando leituras para calcular o ritmo de consumo…","Collecting readings to calculate battery drain…");
        put("Nenhuma atividade recente.","No recent activity.");
        put("Nenhum app restrito automaticamente.","No apps automatically restricted.");
        put("O relógio começa no último momento em que o app esteve em primeiro plano. Apps em uso nunca são congelados.","Timer begins when app leaves foreground. Apps in use are never frozen.");
        put("Aguardar após sair do app antes de congelar","Wait after leaving the app before freezing");
        put("Perfil de ZRAM","ZRAM profile");
        put("Automação inteligente recomendada","Recommended smart automation");
        put("Pré-carregar automaticamente os 4 apps mais usados","Automatically preload the 4 most used apps");
        put("Pré-aquecer até 2 APKs a cada 15 minutos","Warm up to 2 apps every 15 minutes");
        put("Atualizar seleção de apps recentes","Update recent app selection");
        put("Reiniciar aprendizado automático","Reset automatic learning");
        put("Sistema ativo","System active");
        put("revertido","reverted");
        put("amostras","samples");
        put("nova referência","new baseline");
        put("não comprovou","not proven");
        put("aplicativo","app");
        put("bateria baixa","low battery");
        put("Teste automático reversível: uma função por vez, durante 2 minutos","Reversible automatic test: one function at a time for 2 minutes");
        put("Selecionar apps para congelar","Select apps to freeze");
        put("Congelamento apenas em segundo plano","Freeze only in the background");
        put("Apps críticos ficam protegidos. Apps de sistema elegíveis aparecem marcados como [Sistema] e podem ser congelados quando necessário.","Critical apps stay protected. Eligible system apps are marked [System] and can be frozen when needed.");
        put("Buscar aplicativo ou pacote","Search for app or package");
        put("Salvar seleção","Save selection");
        put("Salvar lista","Save list");
        put("Apps que nunca devem ser congelados","Apps that must never be frozen");
        put("Apps marcados ficam fora do congelamento automático","Selected apps are exempt from automatic freezing");
        put("Escolha aqui os apps que nunca devem ser finalizados ou congelados automaticamente. Apps em primeiro plano sempre esperam o período configurado antes de serem congelados.","Select apps that must never be stopped or frozen automatically. Foreground apps are not frozen until the configured delay expires.");
        put("Limpeza avançada","Advanced cleanup");
        put("Libere espaço sem mexer em fotos, vídeos ou documentos pessoais por padrão.","Free up space without deleting your photos, videos or documents by default.");
        put("Ainda não analisado","Not yet analyzed");
        put("Toque em Analisar armazenamento.","Tap Analyze storage.");
        put("Analisar armazenamento","Analyze storage");
        put("Limpar categorias selecionadas","Clean selected categories");
        put("Desfragmentar / otimizar armazenamento (TRIM)","Optimize storage (TRIM)");
        put("Pausar otimização / TRIM","Pause optimization / TRIM");
        put("Aguardando primeira verificação.","Waiting for first check.");
        put("Verificar armazenamento agora","Check storage now");
        put("Nenhuma análise feita.","No analysis yet.");
        put("Localizar arquivos grandes","Find large files");
        put("Selecionar arquivos grandes para excluir","Select large files to delete");
        put("Toque para analisar o histórico de uso.","Tap to analyze usage history.");
        put("Recomendar apps para desinstalar","Recommend apps to uninstall");
        put("Proteção DNS AdGuard","AdGuard DNS protection");
        put("Escolha entre o modo recomendado sem VPN, que protege todo o aparelho, ou o modo experimental por aplicativo.","Choose between recommended VPN-free whole-device protection and experimental per-app mode.");
        put("Modo recomendado • sem VPN","Recommended mode • without VPN");
        put("Usar DNS Privado AdGuard no aparelho inteiro","Use AdGuard Private DNS on the whole device");
        put("Mais estável: usa o DNS Privado nativo do Android e não mantém VPN ou serviço de túnel. Aplica-se a todos os apps.","More stable: uses Android's built-in Private DNS without a VPN or tunnel service. Applies to all apps.");
        put("Modo experimental • por aplicativo","Experimental mode • per app");
        put("Ativar VPN DNS seletiva","Enable selective DNS VPN");
        put("Filtrar todos","Filter all");
        put("Deixar todos livres","Exempt all");
        put("Aplicativos — marcado = AdGuard • desmarcado = livre","Apps — checked = AdGuard • unchecked = bypass");
        put("Carregando aplicativos…","Loading apps…");
        put("Otimizador automático de sinal móvel","Automatic mobile signal optimizer");
        put("Quando o sinal ficar muito baixo, o Adaptive Performance compara as tecnologias permitidas no SIM e mantém a que entregar o melhor sinal.","When signal gets very weak, Adaptive Performance compares allowed SIM network modes and selects the strongest.");
        put("Economia de localização","Location power savings");
        put("Histórico de saúde","Health history");
        put("Analisando…","Analyzing…");
        put("Analisando arquivos grandes…","Analyzing large files…");
        put("Limpando…","Cleaning…");
        put("Otimizando armazenamento…","Optimizing storage…");
        put("Pausando otimização…","Pausing optimization…");
        put("Verificando agora…","Checking now…");
        put("Excluindo arquivos grandes selecionados…","Deleting selected large files…");
        put("Restaurando DNS anterior…","Restoring previous DNS…");
        put("Nenhum app elegível sem uso há mais de 15 dias.","No eligible apps unused for over 15 days.");
        put("0% • parado","0% • stopped");
        put("Economia comprovada", "Verified savings");
        put("Resultado dos testes de 24 horas", "Results of 24-hour trials");
        put("Previsão térmica nativa", "Native thermal forecast");
        put("Diagnóstico temporário", "Temporary diagnostics");
        put("Carregando aplicativos em segundo plano…","Loading apps in the background…");
        put("Falha ao carregar aplicativos: ","Failed to load apps: ");
        put("Mostrar mais aplicativos","Show more apps");
        put("Nenhum aplicativo elegível. Seleção preservada.","No eligible apps. Selection preserved.");
        put("Adaptive Brain 2.0","Adaptive Brain 2.0");
        put("ML contextual, proteção térmica, autorrecuperação e laboratório",
                "Contextual ML, thermal guard, automatic recovery and experiment lab");
        put("Ativar cérebro adaptativo 2.0","Enable Adaptive Brain 2.0");
        put("Aprender próximo aplicativo","Learn next app");
        put("Testar estratégias reversíveis por contexto","Evaluate reversible contextual strategies");
        put("Reconhecer rotinas e proteger navegação/jogos","Recognize routines and protect navigation/games");
        put("Medir fluidez da interface sem monitorar continuamente",
                "Sample UI frame smoothness without constant monitoring");
        put("Resultados e histórico do laboratório","Lab results and history");
        put("Laboratório Adaptive Brain 2.0","Adaptive Brain 2.0 lab");
        put("Aprendizado de máquina local","On-device machine learning");
        put("Personaliza o uso sem servidores ou modelos pesados",
                "Personalizes usage without servers or heavyweight models");
        put("Aprender meus padrões de uso neste aparelho",
                "Learn my usage patterns on this device");
        put("Apagar aprendizado de máquina","Delete learned model");
        put("Modelo local apagado. Aprendizado reiniciado.",
                "Local model deleted. Learning restarted.");
        put("Auditoria de compatibilidade", "Compatibility audit");
        put("Aguardando medição do consumo do próprio aplicativo",
            "Waiting for the app's own resource-use measurement");
        put("Limpar RAM agora","Trim memory now");
        put("Solicitando liberação de memória…","Requesting memory trim…");
        put("Liberação de memória sob demanda","On-demand memory trim");
        put("Solicitação enviada; o Android decide quanto liberar","Request sent; Android decides how much to release");
        put("Shizuku indisponível","Shizuku unavailable");
        put("Shizuku autorizado • acesso shell ativo","Shizuku authorized • shell access active");
        put("Shizuku ativo • aguardando autorização","Shizuku active • waiting for authorization");
        put("Não consegui resolver automaticamente","I couldn't resolve it automatically");
        put("Causa provável detectada","Probable cause detected");
        put("Causa:","Cause:");
        put("O que aconteceu:","What happened:");
        put("Solução sugerida:","Suggested solution:");
        put("Tentar novamente","Try again");
        put("Aplicar solução","Apply solution");
        put("Entendi","Got it");
        put("Manter assim","Keep as is");
        put("Fechar","Close");
        put("Não foi possível iniciar a nova tentativa.","Could not start a new attempt.");
        put("Não foi possível iniciar a correção: ","Could not start the fix: ");
        put("Permita o acesso ao uso dos apps para ativar o reconhecimento automático.","Allow usage access to enable automatic recognition.");
        put("O próximo ciclo vai pré-carregar os apps usados nos últimos 15 minutos.","The next cycle will preload apps used in the last 15 minutes.");
        put("Não foi possível atualizar os apps usados.","Could not update recently used apps.");
        put("Aprendizado automático reiniciado.","Automatic learning reset.");
        put("Não foi possível iniciar a otimização.","Could not start optimization.");
        put("Diagnóstico salvo em Downloads: ","Diagnostics saved to Downloads: ");
        put("Falha ao exportar: ","Export failed: ");
        put("Thermal nível ","Thermal level ");
        put(" mantido manualmente"," held manually");
        put("Proteção térmica automática em ação","Automatic thermal protection active");
        put("Modo anti-travamento forte em ação","Strong anti-stall mode active");
        put("Prevenção de travamentos ativa","Anti-stall protection active");
        put("Apps em segundo plano temporariamente limitados","Background apps temporarily limited");
        put("Desempenho e temperatura sob controle","Performance and temperature under control");
        put("Economia automática ativa","Automatic savings active");
        put("Proteção de pressão ativa • ","Pressure protection active • ");
        put(" apps limitados"," apps limited");
        put("Pressão combinada: normal","Combined pressure: normal");
        put("Nenhuma limitação ativa","No active limits");
        put("Compactar quando RAM livre ≤ ","Compact when free RAM ≤ ");
        put("Limite por app em segundo plano: ","Per-app background limit: ");
        put("Bateria mínima: ","Minimum battery: ");
        put("Horário alvo: ","Target time: ");
        put("O Android pode liberar esse cache a qualquer momento.","Android may release this cache at any time.");
        put("Aguardando coleta de dados…","Waiting for data collection…");
        put("Nenhuma atividade recente.","No recent activity.");
        put("Nenhum app restrito automaticamente.","No apps restricted automatically.");
        put("selecionado(s) • ","selected • ");
        put(" congelado(s) agora"," frozen now");
        put("Aguardando leitura preditiva","Waiting for predictive reading");
        put("Preparando primeiro ciclo de testes","Preparing first test cycle");
        put("Sem testes concluídos","No tests completed");
        put("Fila automática: ","Automatic queue: ");
        put(" ajustes avaliáveis. Primeiro mede uma referência de 2 min; depois testa "," evaluable settings. It first measures a 2-minute baseline, then tests ");
        put("um ajuste por 2 min. Se reverter, mede uma nova referência antes do próximo. ","one setting for 2 minutes. If reverted, it measures a new baseline before the next. ");
        put("Sem medições confiáveis, não aprova. Dependências indisponíveis aparecem como não testadas. ","Without reliable measurements, it does not approve. Unavailable dependencies appear as not tested. ");
        put("Proteções ficam ativas; ações sem restauração ficam desativadas.","Protections stay active; actions without safe restoration stay disabled.");
        put("Configurações automáticas no início da tela. Para opções manuais, selecione Avançado.","Automatic settings are at the top of the screen. Select Advanced for manual options.");
        put("Limitações e inteligência adaptativa","Limits and adaptive intelligence");
        put("Ver o que está limitando agora","See what is limiting the device now");
        put("Estratégia: ","Strategy: ");
        put("Estratégia normal","Normal strategy");
        put("Confiança: ","Confidence: ");
        put("Eficácia: ","Effectiveness: ");
        put("Sem regressão pós-atualização detectada","No post-update regression detected");
        put("Histórico de incidentes e correções","Incident and fix history");
        put("Incidentes e correções","Incidents and fixes");
        put("Nenhum incidente registrado.","No incidents recorded.");
        put("Economia e automação","Savings and automation");
        put("Aguardando dados do monitor…","Waiting for monitor data…");
        put("Reinício recorrente: ","Recurring restart: ");
        put("nenhum","none");
        put("Swap: ","Swap: ");
        put("páginas/s","pages/s");
        put("Compactação automática de RAM","Automatic RAM compaction");
    }
    private UiLanguage(){}
    static boolean english(SharedPreferences prefs) {
        return "en".equals(prefs.getString("app_language","pt"));
    }
    static String tr(SharedPreferences prefs,String raw) {
        if (!english(prefs) || raw == null) return raw;
        String exact = EN.get(raw);
        if (exact != null) return exact;
        String translated = raw;
        for (Map.Entry<String,String> entry : EN.entrySet()) {
            String key = entry.getKey();
            if (key.length() >= 12 && translated.contains(key))
                translated = translated.replace(key,entry.getValue());
        }
        return translated;
    }
}
